apiVersion: apps/v1
kind: Deployment
metadata:
  name: carconsumer-deployment
  labels:
    app: carconsumer
spec:
  selector:
    matchLabels:
      app: carconsumer
  template:
    metadata:
      labels:
        app: carconsumer
    spec:
      containers:
      - name: carconsumer
        image: docker.io/rlkamradt/carconsumer:1.0-SNAPSHOT
        env:
          - name: DATABASE_USER_NAME
            valueFrom:
              secretKeyRef:
                name: cb-example-auth
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cb-example-auth
                key: password
          - name: QUEUE_USER_NAME
            valueFrom:
              secretKeyRef:
                name: myrabbit-default-user
                key: username
          - name: QUEUE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myrabbit-default-user
                key: password
          - name: DATABASE_HOST_NAME
            value: cb-example-srv
          - name: QUEUE_HOST_NAME
            value: myrabbit
